// <auto-generated />
using System;
using Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(CadCliContext))]
    [Migration("20200220201456_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entidades.Cliente", b =>
                {
                    b.Property<long>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasMaxLength(100);

                    b.Property<string>("Cep")
                        .HasMaxLength(9);

                    b.Property<string>("Cidade")
                        .HasMaxLength(100);

                    b.Property<string>("Complemento")
                        .HasMaxLength(100);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250);

                    b.Property<string>("Estado")
                        .HasMaxLength(2);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("Numero");

                    b.Property<int>("Sexo");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");

                    b.HasData(
                        new { ClienteId = 1L, Bairro = "Centro", Cep = "86975-000", Cidade = "Mandaguari", Complemento = "B", DataNascimento = new DateTime(1950, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), Endereco = "Avenida Amazonas", Estado = "PR", Nome = "Maria Oliveira", Numero = 123, Sexo = 0 },
                        new { ClienteId = 2L, Bairro = "Zona 01", Cep = "87013-210", Cidade = "Maringá", DataNascimento = new DateTime(1983, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), Endereco = "Av. Tamandaré", Estado = "PR", Nome = "José da Silva", Numero = 100, Sexo = 1 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
